import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';
import ts from 'typescript-eslint';

export default ts.config(
	// Generated by build / SvelteKit, not linted.
	{
		ignores: ['build/', '.svelte-kit/', 'dist/']
	},
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	// prettier must come last: it turns off style rules that clash with formatting.
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			// TS resolves the symbols; no-undef gives false positives (e.g. runes like $state).
			'no-undef': 'off',
			// Allow discarding bindings with `_` (e.g. `{#each n as _, i}`).
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
			],
			// Dueo is a SPA with fixed string routes; resolve() would only add noise.
			'svelte/no-navigation-without-resolve': 'off',
			// False positives: the flagged Map/Date are local computations inside
			// $derived.by(), not reactive state that needs SvelteMap/SvelteDate.
			'svelte/prefer-svelte-reactivity': 'off'
		}
	},
	{
		// .svelte files (and rune modules .svelte.ts/.js) are parsed with TS.
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				parser: ts.parser
			}
		}
	}
);
